spring:
  application:
    name: booking-management
  datasource:
    url: jdbc:mysql://localhost:3306/bookings
    username: root
    password: chandu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080